<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectTemplate.Application\ProjectTemplate.Application.csproj" />
    <ProjectReference Include="..\ProjectTemplate.Bootstrap\ProjectTemplate.Bootstrap.csproj" />
  </ItemGroup>
</Project>
